variable "name" {
  description = "Name prefix for all resources in this module."
  type        = string
}

variable "environment" {
  description = "Environment name, applied as a tag (dev, prod)."
  type        = string
}

variable "vpc_id" {
  description = "VPC the database security group is created in."
  type        = string
}

variable "private_subnet_ids" {
  description = "Private subnets for the DB subnet group. RDS requires at least two AZs."
  type        = list(string)

  validation {
    condition     = length(var.private_subnet_ids) >= 2
    error_message = "RDS requires a subnet group spanning at least two availability zones."
  }
}

variable "ecs_security_group_id" {
  description = "ECS task security group. The only source allowed to reach the database."
  type        = string
}

variable "db_port" {
  description = "Port the database listens on."
  type        = number
  default     = 5432
}

variable "engine_version" {
  description = "PostgreSQL engine version. A major version (for example \"16\") lets AWS pick the current minor."
  type        = string
  default     = "16"
}

variable "parameter_group_family" {
  description = "Parameter group family, must match engine_version (for example postgres16)."
  type        = string
  default     = "postgres16"
}

variable "db_instance_class" {
  description = "RDS instance class. Sized per environment."
  type        = string
}

variable "allocated_storage" {
  description = "Initial storage in GiB."
  type        = number
}

variable "max_allocated_storage" {
  description = "Upper limit for storage autoscaling in GiB. Must be >= allocated_storage."
  type        = number
}

variable "database_name" {
  description = "Name of the database created on the instance."
  type        = string
}

variable "database_username" {
  description = "Master username. The password is generated by RDS and stored in Secrets Manager."
  type        = string
}

variable "backup_retention_period" {
  description = "Days of automated backups to retain. Longer in prod."
  type        = number

  validation {
    condition     = var.backup_retention_period >= 1 && var.backup_retention_period <= 35
    error_message = "backup_retention_period must be between 1 and 35 days (0 would disable automated backups and point-in-time recovery)."
  }
}

variable "backup_window" {
  description = "Daily UTC window for automated backups."
  type        = string
  default     = "18:00-19:00"
}

variable "maintenance_window" {
  description = "Weekly UTC window for maintenance. Must not overlap backup_window."
  type        = string
  default     = "sun:20:00-sun:21:00"
}

variable "deletion_protection" {
  description = "Block `terraform destroy` on the database. True in prod."
  type        = bool
}

variable "skip_final_snapshot" {
  description = "Skip the final snapshot on deletion. True in dev (disposable data), false in prod."
  type        = bool
}

variable "multi_az" {
  description = "Run a standby in a second AZ for automatic failover."
  type        = bool
}

variable "performance_insights_enabled" {
  description = "Enable Performance Insights."
  type        = bool
  default     = false
}

variable "apply_immediately" {
  description = "Apply changes at once instead of during the maintenance window. True in dev, false in prod to avoid unplanned restarts."
  type        = bool
  default     = false
}

variable "log_min_duration_statement_ms" {
  description = "Log statements slower than this many milliseconds. -1 disables slow query logging."
  type        = number
  default     = 1000
}
