variable "project" {
  description = "Project name, used as the resource name prefix."
  type        = string
  default     = "hotel-booking"
}

variable "environment" {
  description = "Environment name for this root module."
  type        = string

  validation {
    condition     = var.environment == "prod"
    error_message = "This root module is the prod environment; dev lives in ../dev with its own state."
  }
}

variable "aws_region" {
  description = "AWS region to deploy into."
  type        = string
}

variable "plan_only" {
  description = "Use placeholder AWS credentials so `terraform plan` works without AWS access. Set to false for a real apply."
  type        = bool
  default     = true
}

variable "aws_access_key" {
  description = "AWS access key ID. Leave null to use AWS_ACCESS_KEY_ID / an AWS profile instead. Only read when plan_only = false. Never commit a real value."
  type        = string
  default     = null
  sensitive   = true
}

variable "aws_secret_key" {
  description = "AWS secret access key. Leave null to use AWS_SECRET_ACCESS_KEY / an AWS profile instead. Only read when plan_only = false. Never commit a real value."
  type        = string
  default     = null
  sensitive   = true
}


variable "vpc_cidr" {
  description = "CIDR block for the VPC."
  type        = string
}

variable "azs" {
  description = "Availability zones to spread subnets across."
  type        = list(string)
}

variable "single_nat_gateway" {
  description = "Share one NAT gateway across AZs instead of one per AZ."
  type        = bool
}


variable "container_image" {
  description = "Container image for the application task."
  type        = string
}

variable "container_port" {
  description = "Port the container listens on."
  type        = number
}

variable "task_cpu" {
  description = "Fargate task CPU units."
  type        = number
}

variable "task_memory" {
  description = "Fargate task memory in MiB."
  type        = number
}

variable "desired_count" {
  description = "Number of tasks to run."
  type        = number
}

variable "log_retention_days" {
  description = "CloudWatch Logs retention for container logs."
  type        = number
}

variable "container_insights" {
  description = "Enable ECS Container Insights."
  type        = bool
}

variable "alb_deletion_protection" {
  description = "Protect the ALB from accidental deletion."
  type        = bool
}


variable "db_instance_class" {
  description = "RDS instance class."
  type        = string
}

variable "allocated_storage" {
  description = "Initial RDS storage in GiB."
  type        = number
}

variable "max_allocated_storage" {
  description = "Storage autoscaling limit in GiB."
  type        = number
}

variable "database_name" {
  description = "Database name created on the instance."
  type        = string
}

variable "database_username" {
  description = "Master username. The password is generated by RDS into Secrets Manager."
  type        = string
}

variable "backup_retention_period" {
  description = "Days of automated backups to retain."
  type        = number
}

variable "deletion_protection" {
  description = "Block deletion of the database."
  type        = bool
}

variable "skip_final_snapshot" {
  description = "Skip the final snapshot when the database is deleted."
  type        = bool
}

variable "multi_az" {
  description = "Run an RDS standby in a second AZ."
  type        = bool
}

variable "performance_insights_enabled" {
  description = "Enable RDS Performance Insights."
  type        = bool
}

variable "apply_immediately" {
  description = "Apply RDS changes immediately instead of in the maintenance window."
  type        = bool
}
